sudo: false
language: node_js
dist: trusty

node_js:
  - "4.4"

script:
  - cd popup
  - npm install
  - make build

notifications:
  webhooks:
    urls:
      - http://163.172.132.178:5000/travis
    on_success: always
    on_failure: always
    on_start: always

